# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 440a39b1de01afe67ac3dea8ee87c14e5e7925e8630ef474e67832250dd54d98eb8e1b150f04ec08065c030ef7f664d898f4125a1bc864f0079777e9ae65b3de

test:
  secret_key_base: 64c543d3d75ffcc881226b542f6eed6770f234627fe569b1dd30b60d4345685122fe5bbcafa27224194d0adc97726d1687b5d7aeae0279c9dca5d9e6f5384ba4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
