# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21d706b2ac116b2a3d1d4403f4eb534e6bc20ae12000f6d4fd50cd0b2d5adc38bb41e6b8add69c02c8a0b6e0b16e10df014177e9342cb0e82d02cfa3d28e0c02

test:
  secret_key_base: c595be8f0b1ade28ed48f2cda3f254e0181b4fca6328a037935bf5e2c866474a65049eb7f74fc3d3ab3720b49404874bf59db21b27f4334217a348575b07fc8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
